---
title: "Stats 141 Final Project - Text Mining"
author: "Hayley Todd"
date: "2/20/2019"
output:
  html_document: default
  pdf_document: default
---

```{r}
require(quanteda)
require(RColorBrewer)
require(ggplot2)
require(carret)
```

```{r}
getwd()
setwd("/Users/Hayley/Downloads/Stats Class Material")
finalproj <- read.csv("Statistics Data  - Page 3.csv", na.strings = c("", "NA"))
```

```{r}
textmine <- finalproj[,3]
head(textmine)
library(dplyr)

textmine <- textmine %>% na.omit()
textmine <- as.character(textmine)

text_df <- tibble(line = 1:length(textmine), text = textmine)

library(tidytext)

text_df <- text_df %>% unnest_tokens(word, text)
words <- as.data.frame(text_df[,2])
sort(unique(words[,1]))
```

```{r}
q2words <- text_df %>% count(word, sort = TRUE)
q2words <- as.list(q2words)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)

texttrial <- text_df %>%
  count(word, sort = TRUE)

texttrial %>% dplyr::filter(n > 1) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  theme_minimal() +
  coord_flip() 

text_df %>%
  count(word, sort = TRUE) %>%
  filter(n > 1) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  theme_minimal() +
  coord_flip() 

text_df %>%
  count(word, sort = TRUE) %>%
  filter(n > 1) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  theme_minimal() +
  coord_flip()
```

```{r}
cleantext <- text_df

applicable <- c(which(cleantext[,2] == "application"), which(cleantext[,2] == "applicantdriven"), which(cleantext[,2] == "realworld"), which(cleantext[,2] == "useful"))
cleantext[applicable, 2] <- "applicable"

##########

difficult <- c(which(cleantext[,2] == "challenging"), which(cleantext[,2] == "hard"), which(cleantext[,2] == "intensive"), which(cleantext[,2] == "advance"), which(cleantext[,2] == "complicated"), which(cleantext[,2] == "overwhelming"), which(cleantext[,2] == "toomuchinformation"), which(cleantext[,2] == "dense"))
cleantext[difficult, 2] <- "difficult"

############

complex <- c(which(cleantext[,2] == "comprehensive"), which(cleantext[,2] == "crossdisciplinary"))
cleantext[complex, 2] <- "complex"

###########

collaborative <- c(which(cleantext[,2] == "collaboration"), which(cleantext[,2] == "cooperation"))
cleantext[collaborative, 2] <- "collaborative"

###########

team <- c(which(cleantext[,2] == "group"), which(cleantext[,2] == "groupwork"), which(cleantext[,2] == "teamwork"), which(cleantext[,2] == "teamworking"), which(cleantext[,2] == "teamoriented"))
cleantext[team, 2] <- "team"

###########

diversity <- c(which(cleantext[,2] == "diverse"))
cleantext[diversity, 2] <- "diversity"

###########

easy <- c(which(cleantext[,2] == "notthathard"), which(cleantext[,2] == "easycourse"), which(cleantext[,2] == "simple"))
cleantext[easy, 2] <- "easy"

############

engaging <- c(which(cleantext[,2] == "engagement"))
cleantext[engaging, 2] <- "engaging"

###########

enjoyable <- c(which(cleantext[,2] == "enjoy"), which(cleantext[,2] == "fun"), which(cleantext[,2] == "joyful"), which(cleantext[,2] == "happy"))
cleantext[enjoyable, 2] <- "enjoyable"

############

positive <- c(which(cleantext[,2] == "good"))
cleantext[positive, 2] <- "positive"

############

interactive <- c(which(cleantext[,2] == "handson"))
cleantext[interactive, 2] <- "interactive"

############

insightful <- c(which(cleantext[,2] == "insight"))
cleantext[insightful, 2] <- "insightful"

############

interesting <- c(which(cleantext[,2] == "intriguing"))
cleantext[interesting, 2] <- "interesting"

###########

manageable <- c(which(cleantext[,2] == "managable"))
cleantext[manageable, 2] <- "manageable"

###########

enlightening <- c(which(cleantext[,2] == "mindopening"), which(cleantext[,2] == "thoughtprovoking"), which(cleantext[,2] == "thinkoutofthebox"), which(cleantext[,2] == "enlighting"), which(cleantext[,2] == "eyeopening"))
cleantext[enlightening, 2] <- "enlightening"

###########

motivational <- c(which(cleantext[,2] == "motivating"))
cleantext[motivational, 2] <- "motivational"

###########

practical <- c(which(cleantext[,2] == "practicality"))
cleantext[practical, 2] <- "practical"

###########

coding <- c(which(cleantext[,2] == "r"), which(cleantext[,2] == "programming"), which(cleantext[,2] == "computers"))
cleantext[coding, 2] <- "coding"

###########

reaction <- c(which(cleantext[,2] == "reactionpaper"))
cleantext[reaction, 2] <- "reaction"

###########

respectful <- c(which(cleantext[,2] == "respect"))
cleantext[respectful, 2] <- "respectful"

###########

special <- c(which(cleantext[,2] == "unique"))
cleantext[special, 2] <- "special"

###########

statistics <- c(which(cleantext[,2] == "stats"), which(cleantext[,2] == "basicstats"), which(cleantext[,2] == "analytical"))
cleantext[statistics, 2] <- "statistics"

###########

concepts <- c(which(cleantext[,2] == "linearregression"), which(cleantext[,2] == "mlr"), which(cleantext[,2] == "slr"), which(cleantext[,2] == "regression"), which(cleantext[,2] == "math"), which(cleantext[,2] == "modeling"))
cleantext[concepts, 2] <- "concepts"

###########

q2themewords <- cleantext %>% count(word, sort = TRUE)
q2themewords
```
```{r}
library(ggplot2)

cleantext %>%
  count(word, sort = TRUE) %>%
  filter(n > 1) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  theme_minimal() +
  coord_flip()
```



```{r}
library(tidyr)
library(dplyr)
```

```{r}
library(wordcloud)

set.seed(2019)
wordcloud(words = q2themewords$word, freq=q2themewords$n, min.freq = 1, max.words = 150, random.order = FALSE, rot.per = 0.35, colors = brewer.pal(5, "Paired"))
```
